INSERT INTO `products` (`product_name`, `image_name`, `image_path`, `description`, `price`) VALUES
('레트로 티셔츠', 'retro_tshirt.jpg', '/images/products/', '빈티지 스타일의 레트로 티셔츠입니다.', 29000),
('블랙 청바지', 'black_jeans.jpg', '/images/products/', '슬림핏 블랙 데님 청바지.', 45000),
('화이트 스니커즈', 'white_sneakers.jpg', '/images/products/', '깔끔한 디자인의 화이트 스니커즈.', 67000),
('캔버스 백팩', 'canvas_backpack.jpg', '/images/products/', '내구성 좋은 캔버스 소재의 백팩입니다.', 39000),
('우드 시계', 'wood_watch.jpg', '/images/products/', '친환경 우드 소재의 패션 시계.', 53000),
('라운드 선글라스', 'round_sunglasses.jpg', '/images/products/', '빈티지 무드의 라운드 선글라스.', 24000),
('미니멀 반팔 셔츠', 'minimal_shirt.jpg', '/images/products/', '미니멀한 디자인의 반팔 셔츠.', 32000),
('헤링본 자켓', 'herringbone_jacket.jpg', '/images/products/', '고급스러운 헤링본 자켓.', 92000),
('레더 지갑', 'leather_wallet.jpg', '/images/products/', '천연가죽으로 만든 클래식 지갑.', 58000),
('무지 양말 5종 세트', 'socks_set.jpg', '/images/products/', '데일리용 무지 양말 세트.', 15000),
('캐주얼 후드티', 'casual_hoodie.jpg', '/images/products/', '편안한 착용감의 후드티.', 44000),
('스포츠 레깅스', 'sports_leggings.jpg', '/images/products/', '활동성 좋은 스포츠 레깅스.', 37000),
('패딩 점퍼', 'padded_jumper.jpg', '/images/products/', '겨울철 필수 아이템 패딩 점퍼.', 113000),
('니트 스웨터', 'knit_sweater.jpg', '/images/products/', '포근한 소재의 니트 스웨터.', 49000),
('플리츠 스커트', 'pleats_skirt.jpg', '/images/products/', '페미닌한 무드의 플리츠 스커트.', 41000),
('데님 자켓', 'denim_jacket.jpg', '/images/products/', '트렌디한 데님 자켓.', 72000),
('그래픽 티셔츠', 'graphic_tshirt.jpg', '/images/products/', '감각적인 프린팅의 티셔츠.', 28000),
('롱 트렌치코트', 'trench_coat.jpg', '/images/products/', '세련된 실루엣의 트렌치코트.', 98000),
('에코 쇼핑백', 'eco_bag.jpg', '/images/products/', '환경을 생각한 에코 쇼핑백.', 12000),
('클래식 로퍼', 'classic_loafers.jpg', '/images/products/', '정장에 어울리는 클래식 로퍼.', 67000);
